"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Application definition
INSTALLED_APPS = [
    "jazzmin",
    "admin_tools_stats",
    "django_nvd3",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # tiers
    "corsheaders",
    "rest_framework",
    "django_filters",
    # apps
    "users",
    "articles",
    "satisfactions",
    "likes",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://weeb-redis:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


WSGI_APPLICATION = "backend.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_RESET_TIMEOUT = 60 * 60 * 1  # 1 hour


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    # Pagination and filter
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 5,
    # Authentification JWT
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    # Throttling
    "DEFAULT_THROTTLE_RATES": {
        "password_reset": "6/hour",
    },
}

# Override the default user model by using our model
AUTH_USER_MODEL = "users.EmailUser"

# Using our custom EmailBackend for auth
AUTHENTICATION_BACKENDS = ["users.backend.EmailBackend"]

# Customized token
SIMPLE_JWT = {
    "USER_ID_FIELD": "email",
    "USER_ID_CLAIM": "user_email",
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "dev": {
            "format": "[WEEB-BACKEND - {levelname}] {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "dev",
        },
    },
    "loggers": {
        "auth": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "users": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "articles": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}

GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET")
GITHUB_CALLBACK_URL = os.getenv("GITHUB_CALLBACK_URL")

FRONTEND_URL = os.getenv("FRONTEND_URL")


JAZZMIN_SETTINGS = {
    "custom_css": "css/admin_custom.css",
    "site_title": "Weeb Admin",
    "site_header": "Weeb Admin",
    "site_brand": "Dashboard",
    "welcome_sign": "Welcome to Weeb Dashboard",
    "copyright": "Mylena & Pierre",
    # Weeb Logo
    "site_logo": "img/weeb.svg",
    "login_logo": "img/weeb.svg",
    "site_icon": "img/weeb.svg",
    "search_model": [
        "users.EmailUser",
        "articles.Article",
    ],
    "topmenu_links": [
        {"name": "Admin Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "users"},
        {"app": "articles"},
        {"app": "likes"},
        {"app": "satisfactions"},
        # Create issue
        {
            "name": "Issues",
            "url": "https://github.com/mylenasayumi/weeb-backend/issues",
            "new_window": True,
        },
        {
            "name": "Graph",
            "url": "http://127.0.0.1:8000/admin_tools_stats/analytics/",  # to check in prod
            "new_window": True,
        },
    ],
    "order_with_respect_to": ["users", "articles", "likes", "satisfactions"],
    # Icons for each app
    "icons": {
        "auth": "fas fa-users-cog",
        "users.emailuser": "fas fa-user-circle",
        "articles.article": "fas fa-newspaper",
        "likes.like": "fas fa-thumbs-up",
        "satisfactions.satisfaction": "fas fa-face-smile",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    # Dashboard behavior
    "show_ui_builder": False,
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "custom_links": {
        "users": [
            {
                "name": "Create an user",
                "url": "admin:users_emailuser_add",
                "icon": "fas fa-user-plus",
                "permissions": ["users.add_emailuser"],
            }
        ],
        "articles": [
            {
                "name": "Create an article",
                "url": "admin:articles_article_add",
                "icon": "fas fa-plus-circle",
                "permissions": ["articles.add_article"],
            }
        ],
        "satisfactions": [
            {
                "name": "Create a satisfaction form",
                "url": "admin:satisfactions_satisfaction_add",
                "icon": "fas fa-face-smile",
                "permissions": ["satisfactions.add_satisfaction"],
            }
        ],
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "pulse",
    "theme_colour": "purple",
    "navbar": "navbar-primary",
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "sidebar": "sidebar-dark",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "show_ui_builder": False,  # toggle it
    "site_icon": "weeb-favicon.ico",
    "login_logo": None,
}
