# Generated by Django 5.2.7 on 2025-10-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
