# Generated by Django 5.2.7 on 2026-03-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
