# Generated by Django 5.2.7 on 2026-02-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
